---

services:
  app:
    build: .
    environment:
      - ENV=production
      - APP_HOST=${APP_HOST}
      - APP_PORT=${APP_PORT}
      - USE_PUBLIC_IP=${USE_PUBLIC_IP}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db
    entrypoint: >
      sh -c "
        /bin/go-modules-api migrate && 
        /bin/go-modules-api seed 10 && 
        /bin/go-modules-api
      "
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - .:/app

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
